name: Build and Package for MacOS

on:
  push:
    branches:
      - main

jobs:
  build_x86_64:
    runs-on: macos-latest
    name: Build for x86_64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          arch -x86_64 python -m venv venv
          source venv/bin/activate
          arch -x86_64 pip install -r requirements.txt
          arch -x86_64 pip install pyinstaller

      - name: Build executable for x86_64
        run: |
          source venv/bin/activate
          arch -x86_64 pyinstaller run.spec

      - name: Archive x86_64 build
        run: |
          mkdir -p dist/x86_64
          mv dist/run_x86_64 dist/x86_64/run

  build_arm64:
    runs-on: macos-latest
    name: Build for arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          arch -arm64 python -m venv venv
          source venv/bin/activate
          arch -arm64 pip install -r requirements.txt
          arch -arm64 pip install pyinstaller

      - name: Build executable for arm64
        run: |
          source venv/bin/activate
          arch -arm64 pyinstaller run.spec

      - name: Archive arm64 build
        run: |
          mkdir -p dist/arm64
          mv dist/run_arm64 dist/arm64/run

  create_universal_binary:
    runs-on: macos-latest
    needs: [build_x86_64, build_arm64]
    name: Create Universal Binary

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract x86_64 build
        run: |
          mkdir -p dist/x86_64
          tar -xvf dist/x86_64.tar -C dist/x86_64

      - name: Extract arm64 build
        run: |
          mkdir -p dist/arm64
          tar -xvf dist/arm64.tar -C dist/arm64

      - name: Create universal binary
        run: |
          lipo -create -output dist/run dist/x86_64/run dist/arm64/run

      - name: Archive universal binary
        run: |
          mkdir -p output
          zip -r output/macos-executable-universal.zip dist/run

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-executable-universal
          path: output/macos-executable-universal.zip
