name: Build and Package for Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Remove existing venv
      run: |
        if (Test-Path -Path "venv") { Remove-Item -Recurse -Force "venv" }

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'  # 필요에 따라 Python 버전 변경 가능

    - name: Install dependencies
      run: |
        python -m venv venv
        venv\Scripts\activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executable with PyInstaller
      run: |
        venv\Scripts\activate
        pyinstaller run.spec
